import React, { useState } from 'react';
import { Wrench, ChevronDown, ChevronRight, Loader2, Terminal } from 'lucide-react';
import { MarkdownRenderer } from './MarkdownRenderer';
import { ToolCall, ToolResult } from '../types';

interface UnifiedToolBlockProps {
  call: ToolCall;
  result?: ToolResult;
  isCompleted: boolean;
}

export const UnifiedToolBlock: React.FC<UnifiedToolBlockProps> = ({ call, result, isCompleted }) => {
  const [isExpanded, setIsExpanded] = useState(false);

  const functionName = call.function?.name || 'Tool';
  const args = call.function?.arguments || '';
  const hasResult = !!result;

  // Parse result content
  let processedOutput = result?.output || '';
  let isUrl = false;
  let isImage = false;
  let isVideo = false;

  try {
    const parsed = JSON.parse(processedOutput);
    if (Object.keys(parsed).length === 0 || (parsed.status && Object.keys(parsed).length === 1 && !parsed.content && !parsed.results)) {
      processedOutput = '';
    } else {
      processedOutput = JSON.stringify(parsed, null, 2);
    }
  } catch (e) {
    // Not JSON, check for URL
    try {
      const url = new URL(processedOutput);
      if (url.protocol === 'http:' || url.protocol === 'https:') {
        isUrl = true;
        const path = url.pathname.toLowerCase();
        if (/\.(jpeg|jpg|gif|png|webp|svg)$/.test(path)) {
          isImage = true;
        } else if (/\.(mp4|webm|ogg|mov)$/.test(path)) {
          isVideo = true;
        }
      }
    } catch (e2) {
      // Not a valid URL
    }
  }

  return (
    <div className="my-2 border border-purple-200 dark:border-purple-800 rounded-lg overflow-hidden bg-purple-50 dark:bg-purple-900/10">
      {/* Header - Tool Call Info */}
      <button
        onClick={() => setIsExpanded(!isExpanded)}
        className="w-full flex items-center gap-2 px-3 py-2 text-xs font-medium text-purple-700 dark:text-purple-300 hover:bg-purple-100 dark:hover:bg-purple-900/30 transition-colors"
      >
        {isCompleted ? (
          <Wrench className="w-3.5 h-3.5" />
        ) : (
          <Loader2 className="w-3.5 h-3.5 animate-spin" />
        )}
        <span className="truncate font-semibold">{functionName}</span>

        {/* Status indicator */}
        {isCompleted ? (
          <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400 ml-1">
            完成
          </span>
        ) : (
          <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400 ml-1">
            执行中
          </span>
        )}

        {isExpanded ? (
          <ChevronDown className="w-3 h-3 ml-auto shrink-0" />
        ) : (
          <ChevronRight className="w-3 h-3 ml-auto shrink-0" />
        )}
      </button>

      {/* Expanded Content */}
      {isExpanded && (
        <div className="border-t border-purple-200 dark:border-purple-800">
          {/* Arguments Section */}
          <div className="px-3 py-2 bg-white/50 dark:bg-black/20">
            <div className="text-[10px] uppercase tracking-wider text-gray-500 dark:text-gray-400 mb-1 font-semibold">
              参数
            </div>
            <div className="text-xs font-mono text-gray-700 dark:text-gray-300 overflow-x-auto">
              {args || <span className="text-gray-400 italic">无参数</span>}
            </div>
          </div>

          {/* Result Section - Only show if result exists */}
          {hasResult && (
            <div className="px-3 py-2 border-t border-purple-200 dark:border-purple-800 bg-gray-50 dark:bg-gray-900/20">
              <div className="flex items-center gap-1.5 mb-1">
                <Terminal className="w-3 h-3 text-gray-500" />
                <span className="text-[10px] uppercase tracking-wider text-gray-500 dark:text-gray-400 font-semibold">
                  执行结果
                </span>
              </div>
              <div className="text-[13px] text-gray-700 dark:text-gray-300 font-mono overflow-x-auto">
                {isImage ? (
                  <a
                    href={processedOutput}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-500 hover:underline block mb-2 max-w-xs"
                  >
                    <img
                      src={processedOutput}
                      alt={`Generated by ${functionName}`}
                      className="w-full max-h-48 object-contain rounded-md"
                    />
                  </a>
                ) : isVideo ? (
                  <div className="max-w-xs mb-2">
                    <video
                      src={processedOutput}
                      controls
                      className="w-full max-h-48 rounded-md"
                    />
                    <a
                      href={processedOutput}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-blue-500 hover:underline text-xs mt-1 block"
                    >
                      Open video in new tab
                    </a>
                  </div>
                ) : isUrl ? (
                  <a
                    href={processedOutput}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-500 hover:underline break-all"
                  >
                    {processedOutput}
                  </a>
                ) : processedOutput.trim() ? (
                  <MarkdownRenderer content={processedOutput} />
                ) : (
                  <span className="text-gray-500 dark:text-gray-400">无详细输出</span>
                )}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
